version: '3'

services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: "recepdemrci/rdentistry-server:${VERSION}"
    volumes:
      - ./server/:/usr/src/server
      - /usr/src/server/node_modules
    ports:
      - "${PORT_SERVER}:${PORT_SERVER}"
    env_file:
      - .env
    depends_on:
      - db
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: "recepdemrci/rdentistry-client:${VERSION}"
    volumes:
      - ./client/:/usr/src/client
      - /usr/src/client/node_modules
    ports:
      - "${PORT_CLIENT}:${PORT_CLIENT}"
    env_file:
      - .env
    depends_on:
      - server
  db:
    image: postgres:14.6
    ports: 
      - "${PORT_DB}:${PORT_DB}"
    environment:
      - POSTGRES_DB=${DB_DB}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
