version: "3.8"
name: dishekime-dev

services:
  dev-server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    container_name: dev-server
    image: recepdemrci/dishekime-dev-server:${VERSION}
    volumes:
       - ./logs/:/usr/src/server/app/logs
       - ./certs/:/etc/ssl/certs
    ports:
      - 8081:${PORT_SERVER}
    env_file:
      - .env
    depends_on:
      dev-db:
        condition: service_healthy

  dev-client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
      args:
        PORT_CLIENT: ${PORT_CLIENT}
        REACT_APP_API_URL: ${REACT_APP_API_URL}
        REACT_APP_AUTH_URL: ${REACT_APP_AUTH_URL}
        REACT_APP_POLICY_URL: ${REACT_APP_POLICY_URL}
        REACT_APP_TERMS_URL: ${REACT_APP_TERMS_URL}
        REACT_APP_PRICING_URL: ${REACT_APP_PRICING_URL}
    container_name: dev-client
    image: recepdemrci/dishekime-dev-client:${VERSION}
    ports:
      - 3001:${PORT_CLIENT}
    env_file:
      - .env
    depends_on:
      - dev-server

  dev-db:
    container_name: dev-db
    image: postgres:15.3
    restart: always
    volumes:
      - ./db/pgdata/:/var/lib/postgresql/data
    ports:
      - 5431:${DB_PORT}
    environment:
      - POSTGRES_DB=${DB_DB}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5

  nginx:
    image: nginx:latest
    container_name: dev-nginx
    ports:
      - 8800:80
      - 8443:443
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
      - ./certs/:/etc/nginx/certs
    depends_on:
      - dev-client
      - dev-server

  dev-backup:
    build:
      context: ./backup-script
      dockerfile: ./Dockerfile
    container_name: dev-backup
    image: recepdemrci/dishekime-dev-backup:${VERSION}
    volumes:
      - ./backup/:/backup
      - ./logs/:/logs
    env_file:
      - .env
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      dev-server:
        condition: service_started
      dev-db:
        condition: service_healthy
