version: "3.8"
name: rdentistry

services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    container_name: server
    image: recepdemrci/rdentistry-server:${VERSION}
    volumes:
      - ./server/:/usr/src/server
      - /usr/src/server/node_modules
    ports:
      - ${PORT_SERVER}:${PORT_SERVER}
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    container_name: client
    image: recepdemrci/rdentistry-client:${VERSION}
    volumes:
      - ./client/:/usr/src/client
      - /usr/src/client/node_modules
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    depends_on:
      - server

  db:
    container_name: db
    image: postgres:15.3
    restart: always
    volumes:
      - ./db/pgdata/:/var/lib/postgresql/data
    ports:
      - ${DB_PORT_}:${DB_PORT}
    environment:
      - POSTGRES_DB=${DB_DB}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5

  backup:
    build:
      context: ./backup-script
      dockerfile: ./Dockerfile
    container_name: backup
    volumes:
      - ./backup/:/backup
      - ./server/app/logs/:/logs
    env_file:
      - .env
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      server:
        condition: service_started
      db:
        condition: service_healthy
